// Projects feature data
export const MY_PROJECTS_DATA = [
  { id: 'proj1', name: 'Acme Corp HQ', location: 'Indianapolis, IN', image: 'https://webresources.jsifurniture.com/production/uploads/jsi_vision_install_0000010.jpg' },
  { id: 'proj2', name: 'Tech Park Offices', location: 'Fishers, IN', image: 'https://webresources.jsifurniture.com/production/uploads/jsi_caav_install_00024_pldPbiW.jpg' },
  { id: 'proj3', name: 'Community Hospital', location: 'Carmel, IN', image: 'https://webresources.jsifurniture.com/production/uploads/original_images/jsi_finn_enviro_00004_aOu5872.jpg' },
  { id: 'proj4', name: 'Downtown Library', location: 'Indianapolis, IN', image: 'https://webresources.jsifurniture.com/production/uploads/jsi_coldjet_install_00001.jpg' },
];

// Use only valid discount option strings from DISCOUNT_OPTIONS list
export const INITIAL_OPPORTUNITIES = [
  { id: 1, name: 'New Office Furnishings', stage: 'Discovery', discount: '50/20/5 (62.00%)', value: '$50,000', company: 'ABC Corporation', contact: 'John Smith', poTimeframe: '30-60 days', vertical: 'Corporate', winProbability: 50, competitionPresent: true, competitors: ['Steelcase','Haworth'], designFirms: ['McGee Designhouse'], dealers: ['Business Furniture'], products: [{series:'Vision'},{series:'Finn'}], notes: 'Main HQ expansion; awaiting test fit.', quotes:[{id:'q1', fileName:'Quote_100045.pdf', status:'complete', url:'/mock/Quote_100045.pdf', assigneeNames:['Jessica Rodriguez'], completedAt:'2026-02-05T15:30:00.000Z'}] },
  { id: 3, name: 'Corporate Expansion Towers', stage: 'Discovery', discount: '50/20/3 (61.20%)', value: '$180,000', company: 'GlobalTech', contact: 'Sara Lin', poTimeframe: '60-90 days', vertical: 'Corporate', winProbability: 40, competitionPresent: false, competitors: [], designFirms: ['CSO'], dealers: ['RJE'], products: [{series:'Knox'}], notes: 'Early budget phase; spec standards requested.', quotes:[{id:'q2', fileName:'Budget_Set_A.pdf', status:'requested', url:'/mock/Budget_Set_A.pdf', assigneeNames:['Sarah Johnson'], requestedAt:'2026-03-14T10:15:00.000Z'}] },
  { id: 4, name: 'Medical Wing Remodel', stage: 'Discovery', discount: '50/20/2 (60.80%)', value: '$95,000', company: 'Midwest Health', contact: 'Alan Cooper', poTimeframe: '30-60 Days', vertical: 'Healthcare', winProbability: 60, competitionPresent: true, competitors: ['OFS'], designFirms: ['Ratio'], dealers: ['OfficeWorks'], products: [{series:'Coact'}], notes: 'Clinical areas focusing on cleanability.', customerId: 'cust-1' },
  { id: 5, name: 'University Commons Refresh', stage: 'Discovery', discount: '50/20 (60.00%)', value: '$120,000', company: 'State University', contact: 'Emily Raine', poTimeframe: '90+ Days', vertical: 'Education', winProbability: 20, competitionPresent: false, competitors: [], designFirms: ['Studio M'], dealers: ['COE'], products: [{series:'Cao'}, {series:'Wink'}], notes: 'Student collaboration zones & lounge pieces.', quotes:[{id:'q3', fileName:'Student_Lounge_Rev1.pdf', status:'review', url:'/mock/Student_Lounge_Rev1.pdf', assigneeNames:['Michael Chen'], requestedAt:'2026-03-20T13:45:00.000Z'}], customerId: 'cust-3' },
  { id: 6, name: 'Hotel Lobby Seating', stage: 'Discovery', discount: '50/20/6 (62.40%)', value: '$70,000', company: 'Metro Hospitality', contact: 'Chris Dow', poTimeframe: '60-90 days', vertical: 'Hospitality', winProbability: 55, competitionPresent: true, competitors: ['DarRan'], designFirms: ['IDO'], dealers: ['Business Furniture'], products: [{series:'Hoopz'}], notes: 'Boutique brand look; finishes TBD.', customerId: 'cust-5' },
  { id: 7, name: 'Startup Collaboration Space', stage: 'Discovery', discount: '50/20/4 (61.60%)', value: '$42,000', company: 'Innovate Labs', contact: 'Priya Patel', poTimeframe: 'Within 30 Days', vertical: 'Corporate', winProbability: 80, competitionPresent: false, competitors: [], designFirms: ['McGee Designhouse'], dealers: ['RJE'], products: [{series:'Vision'}], notes: 'Fast-track timeline; prioritizing flexible meeting areas.' },
  { id: 2, name: 'Lobby Refresh', stage: 'Specifying', discount: '50/20/8 (63.20%)', value: '$75,000', company: 'XYZ Industries', contact: 'Jane Doe', poTimeframe: '60-90 days', vertical: 'Corporate', winProbability: 65, competitionPresent: true, competitors: ['MillerKnoll'], designFirms: ['CSO'], dealers: ['Business Furniture'], products: [{series:'Vision'},{series:'Wink'}], notes: 'Renderings complete; awaiting final budget approval.', quotes:[{id:'q4', fileName:'Lobby_Renderings.pdf', status:'in-progress', url:'/mock/Lobby_Renderings.pdf', assigneeNames:['David Thompson'], requestedAt:'2026-03-19T09:20:00.000Z'}] },
  { id: 8, name: 'Benchmark Finish Library Refresh', stage: 'Discovery', discount: '50/20/3 (61.20%)', value: '$28,000', company: 'Benchmark Design Group', contact: 'Morgan Reeves', poTimeframe: '30-60 Days', vertical: 'Corporate', winProbability: 45, competitionPresent: false, competitors: [], designFirms: ['Benchmark Design Group'], dealers: ['Business Furniture'], products: [{series:'Vision'}, {series:'Anthology'}], notes: 'Sample order is supporting finish alignment before the first budget pull.', quotes:[{id:'q8', fileName:'Benchmark_Finish_Budget.pdf', status:'in-progress', url:'/mock/Benchmark_Finish_Budget.pdf', assigneeNames:['Sarah Johnson'], requestedAt:'2026-03-22T11:10:00.000Z'}] },
  { id: 9, name: 'Chicago Showroom Standards Reset', stage: 'Won', discount: '50/20/5 (62.00%)', value: '$64,000', company: 'Haworth Chicago Showroom', contact: 'Megan Ross', poTimeframe: 'Within 30 Days', vertical: 'Corporate', winProbability: 100, competitionPresent: true, competitors: ['Kimball'], designFirms: ['Studio M'], dealers: ['Business Furniture'], products: [{series:'Anthology'}, {series:'Vision'}], notes: 'Showroom standards package closed after the sample kit review.', quotes:[{id:'q9a', fileName:'Showroom_Standards_Final.pdf', status:'complete', url:'/mock/Showroom_Standards_Final.pdf', assigneeNames:['Jessica Rodriguez'], completedAt:'2026-02-18T16:05:00.000Z'}, {id:'q9b', fileName:'Accessory_Add_Alt.pdf', status:'complete', url:'/mock/Accessory_Add_Alt.pdf', assigneeNames:['Michael Chen'], completedAt:'2026-02-21T09:40:00.000Z'}] },
  { id: 10, name: 'Mitchell Interiors Material Palette', stage: 'Lost', discount: '50/20/4 (61.60%)', value: '$18,500', company: 'Mitchell Interiors', contact: 'Sarah Mitchell', poTimeframe: '30-60 Days', vertical: 'Corporate', winProbability: 0, competitionPresent: true, competitors: ['Kimball'], designFirms: ['Mitchell Interiors'], dealers: ['OfficeWorks'], products: [{series:'Wink'}], notes: 'Palette review moved forward, but the project ultimately went another direction.', quotes:[{id:'q10', fileName:'Mitchell_Palette_Set.pdf', status:'complete', url:'/mock/Mitchell_Palette_Set.pdf', assigneeNames:['Emily Davis'], completedAt:'2026-01-30T14:10:00.000Z'}] },
  { id: 11, name: 'Perkins&Will Sample Library Update', stage: 'Specifying', discount: '50/20/2 (60.80%)', value: '$22,400', company: 'Perkins&Will', contact: 'Amanda Chen', poTimeframe: '60-180 Days', vertical: 'Corporate', winProbability: 55, competitionPresent: false, competitors: [], designFirms: ['Perkins&Will'], dealers: ['RJE'], products: [{series:'Vision'}, {series:'Knox'}], notes: 'Old sample request rolled into an active standards refresh with a quote still being assembled.', quotes:[{id:'q11', fileName:'PW_Library_Refresh.pdf', status:'review', url:'/mock/PW_Library_Refresh.pdf', assigneeNames:['David Thompson'], requestedAt:'2026-03-16T08:55:00.000Z'}] }
];

export const STAGES = ['Discovery', 'Specifying', 'Decision/Bidding', 'PO Expected', 'Won', 'Lost'];

export const EMPTY_LEAD = { project: '', designFirm: '', dealer: '', winProbability: 50, projectStatus: '', vertical: '', otherVertical: '', estimatedList: '', poTimeframe: '', competitors: [], otherCompetitor: '', competitionPresent: false, isBid: false, jsiSpecServices: false, quoteType: 'New Quote', pastProjectRef: '', discount: '', salesReward: true, designerReward: true, products: [], notes: '', jsiQuoteExists: false, jsiQuoteNumber: '', quoteNeeded: false, expectedInstallDate: '', endUser: '', isContract: false, contractType: '' };

export const URGENCY_LEVELS = ['Low', 'Medium', 'High'];
export const PO_TIMEFRAMES = ['Unknown', 'Within 30 Days', '30-60 Days', '60-180 Days', '180+ Days', 'Next Year'];
export const COMPETITORS = ['None', 'Unknown', 'Kimball', 'OFS', 'Indiana', 'National', 'Haworth', 'HNI', 'MillerKnoll', 'Steelcase', 'Versteel', 'Krug', 'Lazyboy', 'DarRan', 'Hightower', 'Allsteel'];
export { DISCOUNT_OPTIONS, DAILY_DISCOUNT_OPTIONS, DISCOUNT_OPTIONS_WITH_UNKNOWN } from '../../constants/discounts.js';
export { VERTICALS, VERTICAL_COLORS } from '../../constants/verticals.js';
export const WIN_PROBABILITY_OPTIONS = ['20%', '40%', '60%', '80%', '100%'];
export const INITIAL_DESIGN_FIRMS = ['N/A', 'Undecided', 'McGee Designhouse', 'Ratio', 'CSO', 'IDO', 'Studio M'];
export const INITIAL_DEALERS = ['Undecided', 'Business Furniture', 'COE', 'OfficeWorks', 'RJE'];
