// Lead Times specific data
export const LEAD_TIMES_DATA = [
    { series: 'Addison', type: 'Wood Seating', weeks: 4, image: '/series-images/jsi_addison_comp_00015.jpg' },
    { series: 'Addison', type: 'Upholstery', weeks: 7, image: '/series-images/jsi_addison_comp_00014.jpg' },
    { series: 'Americana', type: 'Wood Seating', weeks: 4, image: '/series-images/jsi_americana_comp_00026.jpg' },
    { series: 'Americana', type: 'Upholstery', weeks: 7, image: '/series-images/jsi_americana_comp_00027.jpg' },
    { series: 'Ansen', type: 'Seating', weeks: 7, image: '/series-images/jsi_ansen_comp_00002.jpg' },
    { series: 'Anthology', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_anthology_comp_0008.jpg' },
    { series: 'Arwyn', type: 'Seating', weeks: 8, image: '/series-images/jsi_arwyn_comp_0001.jpg' },
    { series: 'Arwyn', type: 'Tables', weeks: 4, image: '/series-images/jsi_arwyn_comp_0001.jpg' },
    { series: 'Avini', type: 'Seating', weeks: 7, image: '/series-images/jsi_avini_comp_00001.jpg' },
    { series: 'BeSPACE', type: 'Seating', weeks: 8, image: '/series-images/jsi_bespace_comp_00001.jpg' },
    { series: 'BeSPACE', type: 'Tables', weeks: 4, image: '/series-images/jsi_bespace_comp_00001.jpg' },
    { series: 'Boston', type: 'Wood Seating', weeks: 7, image: '/series-images/jsi_boston_comp_00001.jpg' },
    { series: 'Boston', type: 'Upholstery', weeks: 7, image: '/series-images/jsi_boston_comp_00001.jpg' },
    { series: 'Bourne', type: 'Seating', weeks: 5, image: '/series-images/jsi_bourne_comp_00001.jpg' },
    { series: 'Bourne', type: 'Tables', weeks: 8, image: '/series-images/jsi_bourne_comp_00001.jpg' },
    { series: 'Brogan', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_brogan_config_00001.jpg' },
    { series: 'Bryn', type: 'Seating', weeks: 6, image: '/series-images/jsi_bryn_comp_0004.jpg' },
    { series: 'Bryn', type: 'Upholstery', weeks: 6, image: '/series-images/jsi_bryn_comp_0004.jpg' },
    { series: 'Cäav', type: 'Seating', weeks: 8, image: '/series-images/jsi_caav_comp_0005.jpg' },
    { series: 'Cäav', type: 'Tables', weeks: 8, image: '/series-images/jsi_caav_comp_0005.jpg' },
    { series: 'Class Act', type: 'Wood Seating', weeks: 4, image: '/series-images/jsi_class-act_comp_00001.jpg' },
    { series: 'Class Act', type: 'Upholstery', weeks: 7, image: '/series-images/jsi_class-act_comp_00001.jpg' },
    { series: 'Connect', type: 'Seating', weeks: 6, image: '/series-images/jsi_connect_comp_00001.jpg' },
    { series: 'Copilot', type: 'Casegoods', weeks: 6, image: '/series-images/jsi_copilot_config_00001.jpg' },
    { series: 'Cosgrove', type: 'Seating', weeks: 5, image: '/series-images/jsi_cosgrove_comp_00001.jpg' },
    { series: 'Encore', type: 'Seating', weeks: 5, image: '/series-images/jsi_encore_comp_00001.jpg' },
    { series: 'Finale', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_finale_config_00001.jpg' },
    { series: 'Finn', type: 'Seating', weeks: 7, image: '/series-images/jsi_finn_comp_00001.jpg' },
    { series: 'Finn Nu', type: 'Seating', weeks: 7, image: '/series-images/jsi_finn-nu_comp_00001.jpg' },
    { series: 'Flux', type: 'Laminate', weeks: 10, image: '/series-images/jsi_flux_config_00008.jpg' },
    { series: 'Flux', type: 'Veneer', weeks: 10, image: '/series-images/jsi_flux_config_00008.jpg' },
    { series: 'Forge', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_forge_config_0001.jpg' },
    { series: 'Garvey RS', type: 'Seating', weeks: 7, image: '/series-images/jsi_garvey-rs_comp_00001.jpg' },
    { series: 'Gatsby', type: 'Seating', weeks: 6, image: '/series-images/jsi_gatsby_comp_00001.jpg' },
    { series: 'Harbor', type: 'Seating', weeks: 7, image: '/series-images/jsi_harbor_comp_00001.jpg' },
    { series: 'Henley', type: 'Seating', weeks: 7, image: '/series-images/jsi_henley_comp_00001.jpg' },
    { series: 'Henley', type: 'Upholstery', weeks: 7, image: '/series-images/jsi_henley_comp_00001.jpg' },
    { series: 'Hoopz', type: 'Upholstery', weeks: 7, image: '/series-images/jsi_hoopz_comp_00001.jpg' },
    { series: 'Indie', type: 'Seating', weeks: 7, image: '/series-images/jsi_indie_comp_00001.jpg' },
    { series: 'Indie', type: 'Tables', weeks: 4, image: '/series-images/jsi_indie_comp_00001.jpg' },
    { series: 'Jude', type: 'Seating', weeks: 5, image: '/series-images/jsi_jude_comp_00001.jpg' },
    { series: 'Jude', type: 'Upholstery', weeks: 5, image: '/series-images/jsi_jude_comp_00001.jpg' },
    { series: 'Kindera', type: 'Seating', weeks: 8, image: '/series-images/jsi_kindera_comp_00001.jpg' },
    { series: 'Knox', type: 'Seating', weeks: 5, image: '/series-images/jsi_knox_comp_00001.jpg' },
    { series: 'Knox', type: 'Upholstery', weeks: 5, image: '/series-images/jsi_knox_comp_00001.jpg' },
    { series: 'Kyla', type: 'Seating', weeks: 5, image: '/series-images/jsi_kyla_comp_00001.jpg' },
    { series: 'Kyla', type: 'Upholstery', weeks: 5, image: '/series-images/jsi_kyla_comp_00001.jpg' },
    { series: 'Lincoln', type: 'Casegoods', weeks: 4, image: '/series-images/jsi_lincoln_config_00001.jpg' },
    { series: 'Lok', type: 'Casegoods', weeks: 5, image: '/series-images/jsi_lok_config_00001.jpg' },
    { series: 'Mackey', type: 'Seating', weeks: 5, image: '/series-images/jsi_mackey_comp_00001.jpg' },
    { series: 'Mackey', type: 'Upholstery', weeks: 5, image: '/series-images/jsi_mackey_comp_00001.jpg' },
    { series: 'Madison', type: 'Seating', weeks: 7, image: '/series-images/jsi_madison_comp_00001.jpg' },
    { series: 'Mittle', type: 'Seating', weeks: 7, image: '/series-images/jsi_mittle_comp_00001.jpg' },
    { series: 'Moto', type: 'Seating', weeks: 5, image: '/series-images/jsi_moto_config_00001.jpg' },
    { series: 'Moto', type: 'Laminate', weeks: 8, image: '/series-images/jsi_moto_config_00001.jpg' },
    { series: 'Moto', type: 'Veneer', weeks: 8, image: '/series-images/jsi_moto_config_00001.jpg' },
    { series: 'Native Benches', type: 'Seating', weeks: 7, image: '/series-images/jsi_native_config_00001.jpg' },
    { series: 'Native', type: 'Laminate', weeks: 8, image: '/series-images/jsi_native_config_00001.jpg' },
    { series: 'Native', type: 'Veneer', weeks: 8, image: '/series-images/jsi_native_config_00001.jpg' },
    { series: 'Newton', type: 'Seating', weeks: 7, image: '/series-images/jsi_newton_comp_00001.jpg' },
    { series: 'Nosh', type: 'Casegoods', weeks: 5, image: '/series-images/jsi_nosh_config_00001.jpg' },
    { series: 'Oxley', type: 'Seating', weeks: 7, image: '/series-images/jsi_oxley_comp_00001.jpg' },
    { series: 'Pillows', type: 'Seating', weeks: 4, image: '/series-images/jsi_pillows_comp_00001.jpg' },
    { series: 'Poet', type: 'Seating', weeks: 8, image: '/series-images/jsi_poet_comp_00001.jpg' },
    { series: 'Poet', type: 'Tables', weeks: 8, image: '/series-images/jsi_poet_comp_00001.jpg' },
    { series: 'Privacy', type: 'Casegoods', weeks: 4, image: '/series-images/jsi_privacy_config_00001.jpg' },
    { series: 'Prost', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_prost_config_00001.jpg' },
    { series: 'Protocol', type: 'Seating', weeks: 5, image: '/series-images/jsi_protocol_comp_00001.jpg' },
    { series: 'Proxy', type: 'Seating', weeks: 7, image: '/series-images/jsi_proxy_comp_00001.jpg' },
    { series: 'Ramona', type: 'Seating', weeks: 7, image: '/series-images/jsi_ramona_comp_00001.jpg' },
    { series: 'Reef', type: 'Laminate', weeks: 8, image: '/series-images/jsi_reef_config_00001.jpg' },
    { series: 'Reef', type: 'Veneer', weeks: 8, image: '/series-images/jsi_reef_config_00001.jpg' },
    { series: 'Ria', type: 'Seating', weeks: 7, image: '/series-images/jsi_ria_comp_00001.jpg' },
    { series: 'Romy', type: 'Casegoods', weeks: 5, image: '/series-images/jsi_romy_config_00001.jpg' },
    { series: 'Satisse', type: 'Seating', weeks: 5, image: '/series-images/jsi_satisse_comp_00001.jpg' },
    { series: 'Somna', type: 'Seating', weeks: 8, image: '/series-images/jsi_somna_comp_00001.jpg' },
    { series: 'Sosa', type: 'Seating', weeks: 6, image: '/series-images/jsi_sosa_comp_00001.jpg' },
    { series: 'Teekan', type: 'Seating', weeks: 8, image: '/series-images/jsi_teekan_comp_00001.jpg' },
    { series: 'Totem', type: 'Seating', weeks: 5, image: '/series-images/jsi_totem_comp_00001.jpg' },
    { series: 'Trinity', type: 'Seating', weeks: 7, image: '/series-images/jsi_trinity_comp_00001.jpg' },
    { series: 'Vision', type: 'Laminate', weeks: 8, image: '/series-images/jsi_vision_config_000002.jpg' },
    { series: 'Vision', type: 'Veneer', weeks: 8, image: '/series-images/jsi_vision_config_000002.jpg' },
    { series: 'Walden', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_walden_config_00001.jpg' },
    { series: 'Wellington', type: 'Casegoods', weeks: 8, image: '/series-images/jsi_wellington_config_00001.jpg' },
    { series: 'Wink', type: 'Seating', weeks: 3, image: '/series-images/jsi_wink_enviro_00033.jpg' },
    { series: 'Ziva', type: 'Tables', weeks: 4, image: '/series-images/jsi_ziva_comp_00001.jpg' },
].sort((a, b) => a.series.localeCompare(b.series));

export const LEAD_TIME_CATEGORIES = [
    { key: 'all', label: 'All' },
    { key: 'upholstered', label: 'Upholstered' },
    { key: 'wood', label: 'Wood Seating' },
    { key: 'casegoods', label: 'Casegoods' }
];

export const LEAD_TIME_TYPES = [
    'Wood Seating',
    'Upholstery', 
    'Seating',
    'Casegoods',
    'Tables',
    'Laminate',
    'Veneer'
];