export const DISCONTINUED_FINISH_SOURCE_GROUPS = [
    {
        id: 'legacy-finish-matrix',
        label: 'Legacy finish replacement matrix',
        shortLabel: 'Legacy archive',
        kind: 'manual',
        capturedAt: '2026-05-04',
        notes: 'Seed data transcribed from archived discontinued finish references and replacement mapping screenshots.',
    },
    {
        id: 'legacy-walnut-section-screenshot',
        label: 'Legacy walnut mapping screenshot',
        shortLabel: 'Walnut archive',
        kind: 'manual',
        capturedAt: '2026-05-04',
        notes: 'Additional user-provided legacy screenshot covering walnut finish replacements.',
    },
    {
        id: 'user-confirmed-2026-06-update',
        label: 'User-confirmed replacement update',
        shortLabel: 'User update',
        kind: 'manual',
        capturedAt: '2026-05-04',
        notes: 'Direct user-provided update: Alabaster laminate is replaced by Designer White effective 2026-06-01.',
    },
];

export const FINISH_CATEGORIES = [
    'Wood Veneer',
    'Laminate',
    'Metal',
];

export const DISCONTINUED_FINISH_API_ENV = 'VITE_DISCONTINUED_FINISHES_API_URL';

export const DISCONTINUED_FINISHES = [
    {
        id: 'wood-veneer-honey-maple',
        oldName: 'Honey Maple',
        newName: 'Alabaster',
        category: 'Wood Veneer',
        lab: 'V-114',
        discontinuedMonth: '2023-06',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'wood-veneer-cherry-natural',
        oldName: 'Cherry Natural',
        newName: 'Bridal Blanco',
        category: 'Wood Veneer',
        lab: 'V-227',
        discontinuedMonth: '2023-06',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'wood-veneer-oak-golden',
        oldName: 'Oak Golden',
        newName: 'Belair',
        category: 'Wood Veneer',
        lab: 'V-319',
        discontinuedMonth: '2023-06',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'wood-veneer-walnut-classic',
        oldName: 'Walnut Classic',
        newName: 'Florence Walnut',
        category: 'Wood Veneer',
        lab: 'V-408',
        discontinuedMonth: '2022-01',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'wood-veneer-ebony-matte',
        oldName: 'Ebony Matte',
        newName: 'Umber',
        category: 'Wood Veneer',
        lab: 'V-512',
        discontinuedMonth: '2022-01',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'wood-veneer-beech-light',
        oldName: 'Beech Light',
        newName: 'Weathered Ash',
        category: 'Wood Veneer',
        lab: 'V-631',
        discontinuedMonth: '2023-06',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'wood-veneer-auburn',
        oldName: 'Auburn',
        newName: 'Sienna',
        category: 'Wood Veneer',
        sourceSection: 'Walnut',
        sourceCodes: ['#3377', '#3378'],
        sourceIds: ['legacy-walnut-section-screenshot'],
    },
    {
        id: 'wood-veneer-night-owl',
        oldName: 'Night Owl',
        newName: 'Truffle',
        category: 'Wood Veneer',
        sourceSection: 'Walnut',
        sourceCodes: ['#3393', '#3394'],
        sourceIds: ['legacy-walnut-section-screenshot'],
    },
    {
        id: 'wood-veneer-toffee',
        oldName: 'Toffee',
        newName: 'Collectors',
        category: 'Wood Veneer',
        sourceSection: 'Walnut',
        sourceCodes: ['#3397', '#3398'],
        sourceIds: ['legacy-walnut-section-screenshot'],
    },
    {
        id: 'laminate-white-gloss',
        oldName: 'White Gloss',
        newName: 'Designer White',
        category: 'Laminate',
        discontinuedMonth: '2024-03',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'laminate-black-satin',
        oldName: 'Black Satin',
        newName: 'Black',
        category: 'Laminate',
        discontinuedMonth: '2024-03',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'laminate-gray-stone',
        oldName: 'Gray Stone',
        newName: 'Slate Grey',
        category: 'Laminate',
        discontinuedMonth: '2024-03',
        sourceIds: ['legacy-finish-matrix'],
    },
    {
        id: 'laminate-alabaster',
        oldName: 'Alabaster',
        newName: 'Designer White',
        category: 'Laminate',
        effectiveOn: '2026-06-01',
        sourceIds: ['user-confirmed-2026-06-update'],
    },
    {
        id: 'metal-matte-nickel',
        oldName: 'Matte Nickel',
        newName: 'Arctic Silver',
        category: 'Metal',
        discontinuedMonth: '2024-09',
        sourceIds: ['legacy-finish-matrix'],
    },
];