// Install Instructions data (derived from JSI Resources > Documents > Install Instructions)
// Video support is intentionally placeholder-first so real URLs can be added later without UI rework.
export const INSTALL_INSTRUCTIONS_DATA = [
    {
        id: 'be-space',
        title: 'BeSpace Install Instructions',
        series: 'BeSpace',
        type: 'Open Plan',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/BeSpace_Installation_Instructions_Uan35Lh.zip',
        difficulty: 'Intermediate',
        duration: '11:20',
        video: { status: 'planned', url: null },
        tags: ['benching', 'workstations', 'power'],
    },
    {
        id: 'bourne',
        title: 'Bourne Install Instructions',
        series: 'Bourne',
        type: 'Seating',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Bourne_Installation_Instructions_W4X3omj.zip',
        difficulty: 'Beginner',
        duration: '8:40',
        video: { status: 'planned', url: null },
        tags: ['task seating', 'chair', 'assembly'],
    },
    {
        id: 'caav',
        title: 'Caav Install Instructions',
        series: 'Caav',
        type: 'Lounge',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/C%C4%81av_Installation_Instructions_A6s4NzT.zip',
        difficulty: 'Advanced',
        duration: '15:20',
        video: { status: 'planned', url: null },
        tags: ['lounge', 'soft seating', 'modular'],
    },
    {
        id: 'connect',
        title: 'Connect Install Instructions',
        series: 'Connect',
        type: 'Open Plan',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Connect_Installation_Instructions_kqqFVUO.zip',
        difficulty: 'Intermediate',
        duration: '12:35',
        video: { status: 'planned', url: null },
        tags: ['benching', 'frame', 'open office'],
    },
    {
        id: 'ergo',
        title: 'Ergo Install Instructions',
        series: 'Ergo',
        type: 'Seating',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Ergo_Installation_Instructions.zip',
        difficulty: 'Beginner',
        duration: '7:55',
        video: { status: 'planned', url: null },
        tags: ['ergonomic', 'chair', 'adjustments'],
    },
    {
        id: 'flux',
        title: 'Flux Install Instructions',
        series: 'Flux',
        type: 'Seating',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Flux_Installation_Instructions_9f8XzI2.zip',
        difficulty: 'Beginner',
        duration: '9:10',
        video: { status: 'planned', url: null },
        tags: ['stool', 'chair', 'base'],
    },
    {
        id: 'forge',
        title: 'Forge Install Instructions',
        series: 'Forge',
        type: 'Tables',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Forge_Installation_Instructions_e7G42wt.zip',
        difficulty: 'Intermediate',
        duration: '10:50',
        video: { status: 'planned', url: null },
        tags: ['conference', 'table', 'base assembly'],
    },
    {
        id: 'general',
        title: 'General Product Installation Instructions',
        series: 'General',
        type: 'General',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/General_Product_Installation_Instructions.zip',
        difficulty: 'Beginner',
        duration: '6:30',
        video: { status: 'planned', url: null },
        tags: ['general', 'guidelines', 'hardware'],
    },
    {
        id: 'kindera',
        title: 'Kindera Install Instructions',
        series: 'Kindera',
        type: 'Education',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Kindera_Install_Instructions.zip',
        difficulty: 'Intermediate',
        duration: '9:45',
        video: { status: 'planned', url: null },
        tags: ['education', 'learning', 'classroom'],
    },
    {
        id: 'knox',
        title: 'Knox Install Instructions',
        series: 'Knox',
        type: 'Seating',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Knox_Installation_Instructions_drrz6Gm.zip',
        difficulty: 'Beginner',
        duration: '6:45',
        video: { status: 'planned', url: null },
        tags: ['seating', 'stool', 'chair'],
    },
    {
        id: 'lok-training',
        title: 'Lok Training Install Instructions',
        series: 'Lok Training',
        type: 'Education',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Lok_Training_Installation_Instructions_ZGyiXsu.zip',
        difficulty: 'Intermediate',
        duration: '13:15',
        video: { status: 'planned', url: null },
        tags: ['training', 'tables', 'flip top'],
    },
    {
        id: 'moto',
        title: 'Moto Install Instructions',
        series: 'Moto',
        type: 'Seating',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Moto_Installation_Instructions_phIErpB.zip',
        difficulty: 'Beginner',
        duration: '8:15',
        video: { status: 'planned', url: null },
        tags: ['chair', 'task', 'assembly'],
    },
    {
        id: 'native',
        title: 'Native Install Instructions',
        series: 'Native',
        type: 'Casegoods',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Native_Installation_Instructions_ogLaWc9.zip',
        difficulty: 'Advanced',
        duration: '16:10',
        video: { status: 'planned', url: null },
        tags: ['storage', 'casegoods', 'cabinets'],
    },
    {
        id: 'nosh',
        title: 'Nosh Install Instructions',
        series: 'Nosh',
        type: 'Tables',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Nosh_Installation_Instructions_hx8hISo.zip',
        difficulty: 'Intermediate',
        duration: '10:05',
        video: { status: 'planned', url: null },
        tags: ['cafe', 'tables', 'dining'],
    },
    {
        id: 'reef',
        title: 'Reef Install Instructions',
        series: 'Reef',
        type: 'Lounge',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Reef_Installation_Instructions_BsBTPKF.zip',
        difficulty: 'Intermediate',
        duration: '11:50',
        video: { status: 'planned', url: null },
        tags: ['lounge', 'hospitality', 'modular'],
    },
    {
        id: 'satisse',
        title: 'Satisse Install Instructions',
        series: 'Satisse',
        type: 'Seating',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Satisse_Install_Instructions.zip',
        difficulty: 'Beginner',
        duration: '7:20',
        video: { status: 'planned', url: null },
        tags: ['seating', 'stack', 'side chair'],
    },
    {
        id: 'somna',
        title: 'Somna Install Instructions',
        series: 'Somna',
        type: 'Lounge',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Somna_Install_Instructions.zip',
        difficulty: 'Intermediate',
        duration: '12:05',
        video: { status: 'planned', url: null },
        tags: ['soft seating', 'lounge', 'modular'],
    },
    {
        id: 'vision',
        title: 'Vision Install Instructions',
        series: 'Vision',
        type: 'Casegoods',
        pdfUrl: 'https://webresources.jsifurniture.com/production/uploads/Vision_Installation_Instructions_xCfruLQ.zip',
        difficulty: 'Intermediate',
        duration: '12:45',
        video: { status: 'planned', url: null },
        tags: ['casegoods', 'desks', 'storage'],
    },
];

export const INSTRUCTION_TYPES = ['Casegoods', 'Seating', 'Lounge', 'Open Plan', 'Tables', 'Education', 'General'];

export const DIFFICULTY_LEVELS = ['Beginner', 'Intermediate', 'Advanced'];
